version: '3'

services:
  bot:
    # depends_on:
    #   - redis
    # restart: always
    build: ./
    environment:
      - SLACK_BOT_TOKEN
      - SLACK_API_TOKEN
      - DYNAMO_TABLE=bot-brain
      - AWS_REGION=us-east-2
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SECURITY_TOKEN
      - AWS_SESSION_TOKEN
      - AWS_SESSION_EXPIRATION

  # redis:
  #   image: redis:latest
  #   command: redis-server --appendonly yes
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ./redis-brain/data:/data
